"""Langfuse v3 auto-provisioning (``observability.langfuse: true``).

Flipping the toggle generates a Compose stack, creates the secrets it needs exactly once,
bootstraps an org, project, user, and API keys without a single UI click, and returns
``http://<host>:3000``. No application-code change at any point.

Three rules here are not stylistic — getting any of them wrong breaks a Langfuse install in
a way that is hard to diagnose (Langfuse Discussion #1902, GitHub issue #3398):

* **``SALT``, ``ENCRYPTION_KEY``, and ``NEXTAUTH_SECRET`` are generated once and never
  regenerated.** They are the keys existing passwords and API keys were derived under;
  rotating them on a re-run silently invalidates every credential already issued.
* **``SALT`` and ``ENCRYPTION_KEY`` must be identical in the web and worker containers.**
  Two halves of one system disagreeing about the encryption key produces data the other
  cannot read.
* **``LANGFUSE_INIT_*`` values are never quoted in Compose.** A quoted value is taken
  literally, so the bootstrap appears to run and quietly creates an org named ``"acme"``
  including the quotes — or nothing at all.

Secrets are written to ``.env`` and referenced everywhere else by variable *name*. Nothing in
this module logs a secret value, and the generated Compose file interpolates from the
environment rather than embedding them.
"""

from __future__ import annotations

import secrets
from dataclasses import dataclass
from pathlib import Path
from typing import Final

from fasterrag.config.schema import Settings
from fasterrag.observability.logging import get_logger
from fasterrag.services.provisioning import (
    ProvisionResult,
    docker_available,
    port_is_reachable,
    require_provisioning_gate,
    run_docker,
)

__all__ = [
    "COMPOSE_FILE",
    "DEFAULT_LANGFUSE_ROOT",
    "GENERATED_SECRETS",
    "LANGFUSE_PORTS",
    "PRESERVED_SECRETS",
    "WEB_PORT",
    "LangfusePlan",
    "compose_arguments",
    "compose_file",
    "ensure_secrets",
    "explain_failure",
    "read_env",
    "write_env",
]

WEB_PORT: Final = 3000
WORKER_PORT: Final = 3030

# Every port the stack publishes, in the order doctor should check them.
LANGFUSE_PORTS: Final[tuple[int, ...]] = (3000, 3030, 5432, 6379, 8123, 9000, 9090, 9091)

DEFAULT_LANGFUSE_ROOT: Final = Path(".fasterrag") / "langfuse"
COMPOSE_FILE: Final = "docker-compose.yml"
PROJECT_NAME: Final = "fasterrag-langfuse"

# CRITICAL: these three are derived-from, not just used-by. Regenerating any of them on a
# re-run invalidates every password and API key already issued, which presents as users
# unable to log in to a stack that came up healthy.
PRESERVED_SECRETS: Final[tuple[str, ...]] = (
    "LANGFUSE_SALT",
    "LANGFUSE_ENCRYPTION_KEY",
    "LANGFUSE_NEXTAUTH_SECRET",
)

GENERATED_SECRETS: Final[tuple[str, ...]] = (
    *PRESERVED_SECRETS,
    "LANGFUSE_POSTGRES_PASSWORD",
    "LANGFUSE_CLICKHOUSE_PASSWORD",
    "LANGFUSE_MINIO_PASSWORD",
    "LANGFUSE_INIT_USER_PASSWORD",
    "LANGFUSE_PUBLIC_KEY",
    "LANGFUSE_SECRET_KEY",
)

_logger = get_logger(__name__)


@dataclass(frozen=True, slots=True)
class LangfusePlan:
    """Where the stack lives and what it exposes."""

    root: Path
    env_file: Path
    host: str = "localhost"
    web_port: int = WEB_PORT

    @property
    def compose_path(self) -> Path:
        """Return the generated Compose file."""
        return self.root / COMPOSE_FILE

    @property
    def url(self) -> str:
        """Return the URL provisioning reports on success."""
        return f"http://{self.host}:{self.web_port}"


def read_env(path: Path) -> dict[str, str]:
    """Return the variables already present in an env file.

    Values are read but never logged. Reading is what makes generation idempotent: a value
    already present is preserved rather than replaced.
    """
    if not path.is_file():
        return {}

    found: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8-sig").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        name, _, value = stripped.partition("=")
        found[name.strip()] = value.strip()
    return found


def write_env(path: Path, values: dict[str, str], existing: dict[str, str]) -> list[str]:
    """Append newly generated variables to an env file, returning their *names*.

    Only names are returned and logged. Appending rather than rewriting keeps every variable
    an operator put there by hand, which a regenerated file would silently drop.
    """
    added = {name: value for name, value in values.items() if name not in existing}
    if not added:
        return []

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        if path.stat().st_size:
            handle.write("\n")
        handle.write("# Generated by fasterrag provision langfuse. Preserve these values:\n")
        handle.write("# rotating SALT, ENCRYPTION_KEY, or NEXTAUTH_SECRET invalidates every\n")
        handle.write("# password and API key already issued.\n")
        for name, value in added.items():
            handle.write(f"{name}={value}\n")

    return sorted(added)


def ensure_secrets(env_file: Path) -> tuple[dict[str, str], list[str]]:
    """Generate any missing Langfuse secret, preserving every one already present.

    Returns:
        Every value the stack needs, and the *names* of the ones newly generated. Values are
        returned for injection into the subprocess environment and are never logged.
    """
    existing = read_env(env_file)
    values = dict(existing)

    for name in GENERATED_SECRETS:
        if values.get(name):
            continue
        if name.endswith("ENCRYPTION_KEY"):
            # Langfuse requires exactly 256 bits of hex here.
            values[name] = secrets.token_hex(32)
        elif name == "LANGFUSE_PUBLIC_KEY":
            values[name] = f"pk-lf-{secrets.token_hex(16)}"
        elif name == "LANGFUSE_SECRET_KEY":
            values[name] = f"sk-lf-{secrets.token_hex(16)}"
        else:
            values[name] = secrets.token_urlsafe(32)

    created = write_env(env_file, values, existing)
    preserved = [name for name in PRESERVED_SECRETS if name in existing]

    _logger.info(
        "langfuse secrets ensured",
        extra={"generated": created, "preserved": preserved},
    )
    # CRITICAL: only the Langfuse variables are returned. The caller hands this straight to a
    # subprocess environment, and `.env` also holds provider API keys that the Compose stack
    # has no business seeing.
    return {name: values[name] for name in GENERATED_SECRETS}, created


def compose_arguments(plan: LangfusePlan, *verb: str) -> list[str]:
    """Return the ``docker compose`` argv for a verb.

    # CRITICAL: ``--env-file`` is not optional. Compose reads a ``.env`` sitting beside the
    # compose file, and this one lives under ``.fasterrag/langfuse/`` while the secrets live
    # at the project root. Without the flag every ``${...}`` interpolates to the empty string
    # and the stack comes up with blank passwords — Postgres then rejects the web container
    # with an authentication error that reads like a credentials bug rather than a wiring one.
    """
    return [
        "compose",
        "-f",
        str(plan.compose_path),
        "--env-file",
        str(plan.env_file),
        "-p",
        PROJECT_NAME,
        *verb,
    ]


def explain_failure(stderr: str) -> str:
    """Turn a Compose failure into something an operator can act on.

    The tail is kept rather than the head: Compose streams per-layer pull progress to stderr,
    so the first few hundred characters of a failed run are always download noise and the
    actual error is the last thing written.
    """
    tail = stderr.strip()[-400:]

    if "port is already allocated" in tail or "address already in use" in tail:
        ports = ", ".join(str(port) for port in LANGFUSE_PORTS)
        return (
            f"a port the stack needs is already taken. Langfuse publishes {ports}; free the "
            f"conflicting one or stop the other service, then re-run. Compose said: {tail}"
        )
    return f"docker compose failed: {tail}"


def compose_file(plan: LangfusePlan) -> str:
    """Return the Compose stack.

    Secrets are interpolated from the environment by name, never written into this file, so
    the generated Compose can sit beside the code without carrying a credential.

    # CRITICAL: the ``LANGFUSE_INIT_*`` values are unquoted. Compose takes a quoted value
    # literally, so ``LANGFUSE_INIT_ORG_NAME: "fasterRag"`` creates an org whose name
    # includes the quote characters, and the bootstrap appears to have worked.
    """
    return f"""\
# Generated by fasterrag provision langfuse. Do not edit by hand — this file is rewritten
# on every provisioning run. Secrets are interpolated by name from
#   {plan.env_file}
# and are never written here, so running this file needs that env file:
#   docker compose -f {plan.compose_path} --env-file {plan.env_file} -p {PROJECT_NAME} up -d
# Without --env-file every interpolation is empty and the stack starts with blank passwords.
services:
  langfuse-web:
    image: langfuse/langfuse:3
    restart: unless-stopped
    depends_on:
      langfuse-postgres:
        condition: service_healthy
      langfuse-clickhouse:
        condition: service_healthy
      langfuse-minio:
        condition: service_healthy
      langfuse-redis:
        condition: service_healthy
    ports:
      - "{plan.web_port}:3000"
    environment:
      DATABASE_URL: postgresql://postgres:${{LANGFUSE_POSTGRES_PASSWORD}}@langfuse-postgres:5432/postgres
      SALT: ${{LANGFUSE_SALT}}
      ENCRYPTION_KEY: ${{LANGFUSE_ENCRYPTION_KEY}}
      NEXTAUTH_SECRET: ${{LANGFUSE_NEXTAUTH_SECRET}}
      NEXTAUTH_URL: {plan.url}
      CLICKHOUSE_URL: http://langfuse-clickhouse:8123
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ${{LANGFUSE_CLICKHOUSE_PASSWORD}}
      CLICKHOUSE_MIGRATION_URL: clickhouse://langfuse-clickhouse:9000
      # CRITICAL: this stack runs one ClickHouse node. Left at its default the migration
      # issues `CREATE TABLE ... ON CLUSTER default` with `ReplicatedMergeTree`, which a
      # single node rejects for having no Zookeeper — after the Postgres migrations have
      # already succeeded, so the failure looks like a ClickHouse credentials problem.
      CLICKHOUSE_CLUSTER_ENABLED: "false"
      REDIS_CONNECTION_STRING: redis://langfuse-redis:6379
      LANGFUSE_S3_EVENT_UPLOAD_BUCKET: langfuse
      LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: http://langfuse-minio:9000
      LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: minio
      LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: ${{LANGFUSE_MINIO_PASSWORD}}
      LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: "true"
      LANGFUSE_INIT_ORG_ID: fasterrag
      LANGFUSE_INIT_ORG_NAME: fasterRag
      LANGFUSE_INIT_PROJECT_ID: fasterrag
      LANGFUSE_INIT_PROJECT_NAME: fasterRag
      LANGFUSE_INIT_PROJECT_PUBLIC_KEY: ${{LANGFUSE_PUBLIC_KEY}}
      LANGFUSE_INIT_PROJECT_SECRET_KEY: ${{LANGFUSE_SECRET_KEY}}
      LANGFUSE_INIT_USER_EMAIL: admin@fasterrag.local
      LANGFUSE_INIT_USER_NAME: fasterRag admin
      LANGFUSE_INIT_USER_PASSWORD: ${{LANGFUSE_INIT_USER_PASSWORD}}

  langfuse-worker:
    image: langfuse/langfuse-worker:3
    restart: unless-stopped
    depends_on:
      langfuse-postgres:
        condition: service_healthy
      langfuse-clickhouse:
        condition: service_healthy
      langfuse-minio:
        condition: service_healthy
      langfuse-redis:
        condition: service_healthy
    ports:
      - "{WORKER_PORT}:3030"
    environment:
      DATABASE_URL: postgresql://postgres:${{LANGFUSE_POSTGRES_PASSWORD}}@langfuse-postgres:5432/postgres
      # CRITICAL: identical to the web container. Two halves disagreeing about the
      # encryption key produces rows the other cannot read.
      SALT: ${{LANGFUSE_SALT}}
      ENCRYPTION_KEY: ${{LANGFUSE_ENCRYPTION_KEY}}
      CLICKHOUSE_URL: http://langfuse-clickhouse:8123
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ${{LANGFUSE_CLICKHOUSE_PASSWORD}}
      CLICKHOUSE_MIGRATION_URL: clickhouse://langfuse-clickhouse:9000
      CLICKHOUSE_CLUSTER_ENABLED: "false"
      REDIS_CONNECTION_STRING: redis://langfuse-redis:6379
      LANGFUSE_S3_EVENT_UPLOAD_BUCKET: langfuse
      LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: http://langfuse-minio:9000
      LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: minio
      LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: ${{LANGFUSE_MINIO_PASSWORD}}
      LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: "true"

  langfuse-postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${{LANGFUSE_POSTGRES_PASSWORD}}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - langfuse_postgres:/var/lib/postgresql/data

  langfuse-clickhouse:
    image: clickhouse/clickhouse-server:24.3
    restart: unless-stopped
    user: "101:101"
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ${{LANGFUSE_CLICKHOUSE_PASSWORD}}
      CLICKHOUSE_DB: default
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - langfuse_clickhouse:/var/lib/clickhouse
      - langfuse_clickhouse_logs:/var/log/clickhouse-server

  langfuse-redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

  langfuse-minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    restart: unless-stopped
    entrypoint: sh
    # CRITICAL: the bucket is created before the server starts. MinIO does not create one on
    # demand, and Langfuse's event uploads fail against a missing bucket long after the
    # stack has reported itself healthy.
    command: >
      -c 'mkdir -p /data/langfuse && minio server /data
      --address ":9000" --console-address ":9001"'
    ports:
      - "9090:9000"
      - "9091:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: ${{LANGFUSE_MINIO_PASSWORD}}
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - langfuse_minio:/data

volumes:
  langfuse_postgres:
  langfuse_clickhouse:
  langfuse_clickhouse_logs:
  langfuse_minio:
"""


async def provision_langfuse(
    settings: Settings, *, root: Path | None = None, env_file: Path | None = None
) -> ProvisionResult:
    """Generate the stack, create any missing secret, and bring it up.

    Returns:
        The result carrying ``http://<host>:3000``. Re-running converges: the Compose file is
        rewritten, secrets already present are preserved untouched, and ``compose up`` leaves
        healthy containers alone.

    Raises:
        ProvisioningError: If the doctor preflight fails, before any secret is generated.
    """
    plan = LangfusePlan(
        root=(root or DEFAULT_LANGFUSE_ROOT).resolve(),
        env_file=(env_file or Path(".env")).resolve(),
    )

    if not await docker_available():
        return ProvisionResult(
            tool="langfuse",
            status="unavailable",
            detail="docker is not running; start it and re-run",
        )

    # Gated before any secret is generated. This stack claims eight host ports — the widest
    # surface of any toggle — and a conflict discovered mid-`compose up` leaves some
    # containers running and some not.
    await require_provisioning_gate(settings)

    _, created = ensure_secrets(plan.env_file)

    plan.root.mkdir(parents=True, exist_ok=True)
    plan.compose_path.write_text(compose_file(plan), encoding="utf-8")

    result = await run_docker(compose_arguments(plan, "up", "-d"), timeout=900.0)

    if not result.ok:
        return ProvisionResult(
            tool="langfuse",
            status="failed",
            detail=explain_failure(result.stderr),
        )

    _logger.info(
        "langfuse stack started",
        extra={
            "url": plan.url,
            "secrets_generated": created,
            "compose": str(plan.compose_path),
        },
    )
    return ProvisionResult(
        tool="langfuse",
        status="running",
        url=plan.url,
        detail=(
            f"{len(created)} secret(s) generated into {plan.env_file.name}"
            if created
            else f"existing secrets in {plan.env_file.name} preserved"
        ),
    )


async def langfuse_status(*, root: Path | None = None) -> ProvisionResult:
    """Report whether the stack is answering."""
    plan = LangfusePlan(
        root=(root or DEFAULT_LANGFUSE_ROOT).resolve(), env_file=Path(".env").resolve()
    )

    if not await docker_available():
        return ProvisionResult(
            tool="langfuse", status="unavailable", detail="docker is not running"
        )

    reachable = port_is_reachable(plan.host, plan.web_port)
    return ProvisionResult(
        tool="langfuse",
        status="running" if reachable else "stopped",
        url=plan.url if reachable else None,
        detail=f"port {plan.web_port} {'reachable' if reachable else 'not reachable'}",
    )


async def stop_langfuse(*, root: Path | None = None) -> ProvisionResult:
    """Stop the stack, preserving its volumes and its secrets.

    ``down`` without ``--volumes``: dropping the volumes would destroy every trace the stack
    has collected, and an operator asking to stop a service has not asked for that.
    """
    plan = LangfusePlan(
        root=(root or DEFAULT_LANGFUSE_ROOT).resolve(), env_file=Path(".env").resolve()
    )

    if not plan.compose_path.is_file():
        return ProvisionResult(
            tool="langfuse", status="stopped", detail="no generated stack to stop"
        )

    await run_docker(compose_arguments(plan, "down"), timeout=300.0)
    return ProvisionResult(
        tool="langfuse",
        status="stopped",
        detail="containers stopped; volumes and .env secrets preserved",
    )
